//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidyoIntegration.VidyoService.VidyoPortalReplayService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class GeneralFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Exception generalFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GeneralFault", IsNullable=true, Order=0)]
        public Exception GeneralFault1 {
            get {
                return this.generalFault1Field;
            }
            set {
                this.generalFault1Field = value;
                this.RaisePropertyChanged("GeneralFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replay.vidyo.com/apiservice")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object exception1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", IsNullable=true, Order=0)]
        public object Exception1 {
            get {
                return this.exception1Field;
            }
            set {
                this.exception1Field = value;
                this.RaisePropertyChanged("Exception1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replay.vidyo.com/apiservice")]
    public partial class Record : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string guidField;
        
        private string tenantNameField;
        
        private string userNameField;
        
        private string userFullNameField;
        
        private System.DateTime dateCreatedField;
        
        private string dateCreatedStringField;
        
        private System.Nullable<System.DateTime> endTimeField;
        
        private string durationField;
        
        private string resolutionField;
        
        private int framerateField;
        
        private string pinField;
        
        private string recordScopeField;
        
        private string titleField;
        
        private string roomNameField;
        
        private string fileLinkField;
        
        private string recorderIdField;
        
        private bool webcastField;
        
        private string tagsField;
        
        private string commentsField;
        
        private bool lockedField;
        
        private string externalPlaybackLinkField;
        
        private string fileSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tenantName {
            get {
                return this.tenantNameField;
            }
            set {
                this.tenantNameField = value;
                this.RaisePropertyChanged("tenantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string userFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
                this.RaisePropertyChanged("userFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime dateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("dateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string dateCreatedString {
            get {
                return this.dateCreatedStringField;
            }
            set {
                this.dateCreatedStringField = value;
                this.RaisePropertyChanged("dateCreatedString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
                this.RaisePropertyChanged("resolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int framerate {
            get {
                return this.framerateField;
            }
            set {
                this.framerateField = value;
                this.RaisePropertyChanged("framerate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string recordScope {
            get {
                return this.recordScopeField;
            }
            set {
                this.recordScopeField = value;
                this.RaisePropertyChanged("recordScope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string roomName {
            get {
                return this.roomNameField;
            }
            set {
                this.roomNameField = value;
                this.RaisePropertyChanged("roomName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string fileLink {
            get {
                return this.fileLinkField;
            }
            set {
                this.fileLinkField = value;
                this.RaisePropertyChanged("fileLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string recorderId {
            get {
                return this.recorderIdField;
            }
            set {
                this.recorderIdField = value;
                this.RaisePropertyChanged("recorderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool webcast {
            get {
                return this.webcastField;
            }
            set {
                this.webcastField = value;
                this.RaisePropertyChanged("webcast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("tags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
                this.RaisePropertyChanged("locked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string externalPlaybackLink {
            get {
                return this.externalPlaybackLinkField;
            }
            set {
                this.externalPlaybackLinkField = value;
                this.RaisePropertyChanged("externalPlaybackLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("fileSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class AccessViolationFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Exception accessViolationFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccessViolationFault", IsNullable=true, Order=0)]
        public Exception AccessViolationFault1 {
            get {
                return this.accessViolationFault1Field;
            }
            set {
                this.accessViolationFault1Field = value;
                this.RaisePropertyChanged("AccessViolationFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://replay.vidyo.com/apiservice", ConfigurationName="VidyoPortalReplayService.VidyoReplayContentManagementServicePortType")]
    public interface VidyoReplayContentManagementServicePortType {
        
        // CODEGEN: Generating message contract since the operation RecordsSearch is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RecordsSearch", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalReplayService.GeneralFault), Action="RecordsSearch", Name="GeneralFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse1 RecordsSearch(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RecordsSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse1> RecordsSearchAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1 request);
        
        // CODEGEN: Generating message contract since the operation RecordsById is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RecordsById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalReplayService.GeneralFault), Action="RecordsById", Name="GeneralFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdResponse RecordsById(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RecordsById", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdResponse> RecordsByIdAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest request);
        
        // CODEGEN: Generating message contract since the operation UpdateRecord is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="UpdateRecord", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalReplayService.AccessViolationFault), Action="UpdateRecord", Name="AccessViolationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalReplayService.GeneralFault), Action="UpdateRecord", Name="GeneralFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse1 UpdateRecord(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdateRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse1> UpdateRecordAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1 request);
        
        // CODEGEN: Generating message contract since the operation DeleteRecord is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="DeleteRecord", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalReplayService.AccessViolationFault), Action="DeleteRecord", Name="AccessViolationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(VidyoIntegration.VidyoService.VidyoPortalReplayService.GeneralFault), Action="DeleteRecord", Name="GeneralFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse1 DeleteRecord(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DeleteRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse1> DeleteRecordAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class RecordsSearchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tenantNameField;
        
        private string roomFilterField;
        
        private string usernameFilterField;
        
        private string queryField;
        
        private System.Nullable<recordScopeFilter> recordScopeField;
        
        private System.Nullable<sortBy> sortByField;
        
        private System.Nullable<sortDirection> dirField;
        
        private System.Nullable<int> limitField;
        
        private System.Nullable<int> startField;
        
        private System.Nullable<bool> webcastField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string tenantName {
            get {
                return this.tenantNameField;
            }
            set {
                this.tenantNameField = value;
                this.RaisePropertyChanged("tenantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string roomFilter {
            get {
                return this.roomFilterField;
            }
            set {
                this.roomFilterField = value;
                this.RaisePropertyChanged("roomFilter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string usernameFilter {
            get {
                return this.usernameFilterField;
            }
            set {
                this.usernameFilterField = value;
                this.RaisePropertyChanged("usernameFilter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<recordScopeFilter> recordScope {
            get {
                return this.recordScopeField;
            }
            set {
                this.recordScopeField = value;
                this.RaisePropertyChanged("recordScope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<sortBy> sortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
                this.RaisePropertyChanged("sortBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<sortDirection> dir {
            get {
                return this.dirField;
            }
            set {
                this.dirField = value;
                this.RaisePropertyChanged("dir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> webcast {
            get {
                return this.webcastField;
            }
            set {
                this.webcastField = value;
                this.RaisePropertyChanged("webcast");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replay.vidyo.com/apiservice")]
    public enum recordScopeFilter {
        
        /// <remarks/>
        all,
        
        /// <remarks/>
        allUser,
        
        /// <remarks/>
        @new,
        
        /// <remarks/>
        @private,
        
        /// <remarks/>
        organizational,
        
        /// <remarks/>
        @public,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replay.vidyo.com/apiservice")]
    public enum sortBy {
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        title,
        
        /// <remarks/>
        room,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replay.vidyo.com/apiservice")]
    public enum sortDirection {
        
        /// <remarks/>
        ASC,
        
        /// <remarks/>
        DESC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class RecordsSearchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int allVideosCountField;
        
        private int searchCountField;
        
        private int myVideosCountField;
        
        private int webcastCountField;
        
        private int newCountField;
        
        private int privateCountField;
        
        private int organizationalCountField;
        
        private int publicCountField;
        
        private Record[] recordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int allVideosCount {
            get {
                return this.allVideosCountField;
            }
            set {
                this.allVideosCountField = value;
                this.RaisePropertyChanged("allVideosCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int searchCount {
            get {
                return this.searchCountField;
            }
            set {
                this.searchCountField = value;
                this.RaisePropertyChanged("searchCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int myVideosCount {
            get {
                return this.myVideosCountField;
            }
            set {
                this.myVideosCountField = value;
                this.RaisePropertyChanged("myVideosCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int webcastCount {
            get {
                return this.webcastCountField;
            }
            set {
                this.webcastCountField = value;
                this.RaisePropertyChanged("webcastCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int newCount {
            get {
                return this.newCountField;
            }
            set {
                this.newCountField = value;
                this.RaisePropertyChanged("newCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int privateCount {
            get {
                return this.privateCountField;
            }
            set {
                this.privateCountField = value;
                this.RaisePropertyChanged("privateCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int organizationalCount {
            get {
                return this.organizationalCountField;
            }
            set {
                this.organizationalCountField = value;
                this.RaisePropertyChanged("organizationalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int publicCount {
            get {
                return this.publicCountField;
            }
            set {
                this.publicCountField = value;
                this.RaisePropertyChanged("publicCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("records", Order=8)]
        public Record[] records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordsSearchRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest RecordsSearchRequest;
        
        public RecordsSearchRequest1() {
        }
        
        public RecordsSearchRequest1(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest RecordsSearchRequest) {
            this.RecordsSearchRequest = RecordsSearchRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordsSearchResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse RecordsSearchResponse;
        
        public RecordsSearchResponse1() {
        }
        
        public RecordsSearchResponse1(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse RecordsSearchResponse) {
            this.RecordsSearchResponse = RecordsSearchResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecordsByIdRequest", Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public int[] RecordsByIdRequest1;
        
        public RecordsByIdRequest() {
        }
        
        public RecordsByIdRequest(int[] RecordsByIdRequest1) {
            this.RecordsByIdRequest1 = RecordsByIdRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecordsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("records", IsNullable=false)]
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.Record[] RecordsResponse;
        
        public RecordsByIdResponse() {
        }
        
        public RecordsByIdResponse(VidyoIntegration.VidyoService.VidyoPortalReplayService.Record[] RecordsResponse) {
            this.RecordsResponse = RecordsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class UpdateRecordRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        private string commentsField;
        
        private string tagsField;
        
        private System.Nullable<recordScopeUpdate> recordScopeField;
        
        private bool recordScopeFieldSpecified;
        
        private string pinField;
        
        private System.Nullable<recordLocked> lockedField;
        
        private bool lockedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("tags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<recordScopeUpdate> recordScope {
            get {
                return this.recordScopeField;
            }
            set {
                this.recordScopeField = value;
                this.RaisePropertyChanged("recordScope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordScopeSpecified {
            get {
                return this.recordScopeFieldSpecified;
            }
            set {
                this.recordScopeFieldSpecified = value;
                this.RaisePropertyChanged("recordScopeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<recordLocked> locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
                this.RaisePropertyChanged("locked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lockedSpecified {
            get {
                return this.lockedFieldSpecified;
            }
            set {
                this.lockedFieldSpecified = value;
                this.RaisePropertyChanged("lockedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replay.vidyo.com/apiservice")]
    public enum recordScopeUpdate {
        
        /// <remarks/>
        @private,
        
        /// <remarks/>
        organization,
        
        /// <remarks/>
        @public,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://replay.vidyo.com/apiservice")]
    public enum recordLocked {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class UpdateRecordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OK okField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OK OK {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
                this.RaisePropertyChanged("OK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public enum OK {
        
        /// <remarks/>
        OK,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRecordRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest UpdateRecordRequest;
        
        public UpdateRecordRequest1() {
        }
        
        public UpdateRecordRequest1(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest UpdateRecordRequest) {
            this.UpdateRecordRequest = UpdateRecordRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRecordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse UpdateRecordResponse;
        
        public UpdateRecordResponse1() {
        }
        
        public UpdateRecordResponse1(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse UpdateRecordResponse) {
            this.UpdateRecordResponse = UpdateRecordResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class DeleteRecordRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://replay.vidyo.com/apiservice")]
    public partial class DeleteRecordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OK okField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OK OK {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
                this.RaisePropertyChanged("OK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecordRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest DeleteRecordRequest;
        
        public DeleteRecordRequest1() {
        }
        
        public DeleteRecordRequest1(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest DeleteRecordRequest) {
            this.DeleteRecordRequest = DeleteRecordRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRecordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://replay.vidyo.com/apiservice", Order=0)]
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse DeleteRecordResponse;
        
        public DeleteRecordResponse1() {
        }
        
        public DeleteRecordResponse1(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse DeleteRecordResponse) {
            this.DeleteRecordResponse = DeleteRecordResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VidyoReplayContentManagementServicePortTypeChannel : VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VidyoReplayContentManagementServicePortTypeClient : System.ServiceModel.ClientBase<VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType>, VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType {
        
        public VidyoReplayContentManagementServicePortTypeClient() {
        }
        
        public VidyoReplayContentManagementServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VidyoReplayContentManagementServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VidyoReplayContentManagementServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VidyoReplayContentManagementServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse1 VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.RecordsSearch(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1 request) {
            return base.Channel.RecordsSearch(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse RecordsSearch(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest RecordsSearchRequest) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1();
            inValue.RecordsSearchRequest = RecordsSearchRequest;
            VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse1 retVal = ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).RecordsSearch(inValue);
            return retVal.RecordsSearchResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse1> VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.RecordsSearchAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1 request) {
            return base.Channel.RecordsSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchResponse1> RecordsSearchAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest RecordsSearchRequest) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsSearchRequest1();
            inValue.RecordsSearchRequest = RecordsSearchRequest;
            return ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).RecordsSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdResponse VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.RecordsById(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest request) {
            return base.Channel.RecordsById(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.Record[] RecordsById(int[] RecordsByIdRequest1) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest();
            inValue.RecordsByIdRequest1 = RecordsByIdRequest1;
            VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdResponse retVal = ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).RecordsById(inValue);
            return retVal.RecordsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdResponse> VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.RecordsByIdAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest request) {
            return base.Channel.RecordsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdResponse> RecordsByIdAsync(int[] RecordsByIdRequest1) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.RecordsByIdRequest();
            inValue.RecordsByIdRequest1 = RecordsByIdRequest1;
            return ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).RecordsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse1 VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.UpdateRecord(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1 request) {
            return base.Channel.UpdateRecord(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse UpdateRecord(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest UpdateRecordRequest) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1();
            inValue.UpdateRecordRequest = UpdateRecordRequest;
            VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse1 retVal = ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).UpdateRecord(inValue);
            return retVal.UpdateRecordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse1> VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.UpdateRecordAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1 request) {
            return base.Channel.UpdateRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordResponse1> UpdateRecordAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest UpdateRecordRequest) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.UpdateRecordRequest1();
            inValue.UpdateRecordRequest = UpdateRecordRequest;
            return ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).UpdateRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse1 VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.DeleteRecord(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1 request) {
            return base.Channel.DeleteRecord(request);
        }
        
        public VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse DeleteRecord(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest DeleteRecordRequest) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1();
            inValue.DeleteRecordRequest = DeleteRecordRequest;
            VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse1 retVal = ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).DeleteRecord(inValue);
            return retVal.DeleteRecordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse1> VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType.DeleteRecordAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1 request) {
            return base.Channel.DeleteRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordResponse1> DeleteRecordAsync(VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest DeleteRecordRequest) {
            VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1 inValue = new VidyoIntegration.VidyoService.VidyoPortalReplayService.DeleteRecordRequest1();
            inValue.DeleteRecordRequest = DeleteRecordRequest;
            return ((VidyoIntegration.VidyoService.VidyoPortalReplayService.VidyoReplayContentManagementServicePortType)(this)).DeleteRecordAsync(inValue);
        }
    }
}
